name: Run Cucumber Tests by Tags

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        run: mvn -B clean verify

      - name: Run Cucumber Tests by Tags
        run: mvn test -Dcucumber.options="--tags @test"
