name: ebook UI smoke tests On demand
<<<<<<< HEAD

=======
 
>>>>>>> 28ecb57a2761f3f5f53702de609d694275ade027
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
<<<<<<< HEAD


run-name: ebooks UI Smoke Tests by @${{ github.actor }}


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  tests-run:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Clean the project
        run: mvn clean

      - name: Run tests
        run: mvn test

      - name: Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: target/reports
=======
 
    
run-name: ebooks UI Smoke Tests by @${{ github.actor }}
 
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 
  tests-run:
    runs-on: windows-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
 
 
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
 
    - name: Clean the project
      run: mvn clean
 
    - name: Run tests
      run: mvn test
 
    - name: Test Reports
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: target/reports
>>>>>>> 28ecb57a2761f3f5f53702de609d694275ade027
